[package]
name = "tsp-ils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rayon = "1.8.0"
statrs = "0.16.0"
